































}    fun getCartItems(userId: String, callback: (List<CartModel>, Boolean, String) -> Unit)    fun getFileNameFromUri(context: Context, uri: Uri): String?    fun uploadImage(context: Context, imageUri: Uri, callback: (String?) -> Unit)    fun addToCart(productId: String, userId: String, callback: (Boolean, String) -> Unit)                                  Boolean, String) -> Unit)    fun getAllProducts(callback: (List<ProductModel>?,                       -> Unit)                       callback: (ProductModel?,Boolean, String)    fun getProductById(productId: String,                      callback: (Boolean, String) -> Unit)    fun deleteProduct(productId: String,                      callback: (Boolean,String) -> Unit)    fun updateProduct(productId:String,data : MutableMap<String,Any>,                   callback:(Boolean,String) -> Unit)    fun addProduct(productModel: ProductModel,interface ProductRepository {import com.example.semproject.model.ProductModelimport android.net.Uriimport android.content.Contextpackage com.example.semproject.repository